apiVersion: v1
kind: ConfigMap
metadata:
  name: httpbin-config
  labels:
    app: httpbin
data:
  AUDIT_DB_HOST: {{ .Values.httpbin.audit.db.host | quote }}
  AUDIT_DB_PORT: {{ .Values.httpbin.audit.db.port | quote }}
  AUDIT_DB_NAME: {{ .Values.httpbin.audit.db.name | quote }}
  AUDIT_DB_USER: {{ .Values.httpbin.audit.db.user | quote }}
  AUDIT_RETENTION_DAYS: {{ .Values.httpbin.audit.retention.days | quote }}
  MYSQL_DATABASE: {{ .Values.httpbin.mysql.database | quote }}
  MYSQL_USER: {{ .Values.httpbin.mysql.user | quote }}