apiVersion: v1
kind: Secret
metadata:
  name: httpbin-secret
  labels:
    app: httpbin
type: Opaque
stringData:
  AUDIT_DB_PASSWORD: {{ .Values.httpbin.audit.db.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.httpbin.mysql.root.password | quote }}
  MYSQL_PASSWORD: {{ .Values.httpbin.mysql.password | quote }}