apiVersion: v1
kind: Secret
metadata:
  name: httpbin-audit-secret
  labels:
    app: httpbin
type: Opaque
stringData:
  AUDIT_DB_USER: {{ .Values.audit.db.user | quote }}
  AUDIT_DB_PASSWORD: {{ .Values.audit.db.password | quote }}
