# Harness Variables and Secrets
image: <+artifacts.primary.image>

httpbin:
  db:
    host: <+variable.audit_db_host>
    port: <+variable.audit_db_port>
    name: <+variable.audit_db_name>
    user: <+secrets.getValue("audit_db_user")>
    password: <+secrets.getValue("audit_db_password")>
  audit:
    retention_days: <+variable.audit_retention_days>